#!/usr/bin/env node
/**
 * scripts/buildDisposableDomains.mjs
 *
 * Builds the canonical data/disposable_domains.txt from:
 *   - index.json (third-party aggregator list, ~120k entries)
 *   - data/disposable_domains.curated.txt (our additions / overrides, optional)
 *
 * Output is sorted, deduped, shape-validated, lowercased, with hardcoded
 * exclusions for legit services that aggregator lists sometimes mis-tag.
 *
 * Re-run anytime to refresh:
 *
 *     node scripts/buildDisposableDomains.mjs
 *
 * Optional flags:
 *
 *     --input <path>      Override index.json path
 *                         (default: ./index.json)
 *     --curated <path>    Override curated additions path
 *                         (default: ./data/disposable_domains.curated.txt)
 *     --output <path>     Override output path
 *                         (default: ./data/disposable_domains.txt)
 *     --no-curated        Skip the curated additions file even if present
 *
 * Exits non-zero on parse failure or if input is missing.
 *
 * The script is idempotent: running twice on the same inputs produces a
 * byte-identical output. That makes git diffs predictable.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
function flag(name, fallback) {
  const i = args.indexOf(`--${name}`);
  if (i === -1) return fallback;
  return args[i + 1];
}
const HAS_NO_CURATED = args.includes('--no-curated');

const ROOT = process.cwd();
const INPUT_JSON   = resolve(ROOT, flag('input',   'index.json'));
const CURATED_TXT  = resolve(ROOT, flag('curated', 'data/disposable_domains.curated.txt'));
const OUTPUT_TXT   = resolve(ROOT, flag('output',  'data/disposable_domains.txt'));

// ---------------------------------------------------------------------------
// Header (regenerated every run, kept verbatim)
// ---------------------------------------------------------------------------

const HEADER = `# Disposable email provider domains.
#
# Bundled at build time, NOT fetched at runtime. Generated by
# scripts/buildDisposableDomains.mjs - do NOT edit this file directly,
# add domains to data/disposable_domains.curated.txt and re-run the
# build script.
#
# Lines starting with # and blank lines are ignored.
# All entries are lowercase. Comparison is exact (case-insensitive) on
# the email's domain part. Subdomains are NOT auto-matched - if a
# service uses subdomains for aliases, each one is listed explicitly.
#
# Source priority:
#   1. data/disposable_domains.curated.txt (this team's overrides)
#   2. index.json (third-party aggregator list)
#
# Excluded by policy (real services, NOT disposable):
#   - protonmail.com / proton.me / pm.me     (privacy mail)
#   - tutanota.com / tutamail.com / tuta.io  (privacy mail)
#   - qq.com / sohu.com / 163.com / 126.com  (mainstream Chinese)
#   - sina.com / sina.cn / aliyun.com
#   - hushmail.com / fastmail.com / fastmail.fm
#   - gmail.com / yahoo.com (and locales) / outlook.com / icloud.com
#   - aol.com / gmx.* / me.com / live.com / msn.com
#   - mail.ru / yandex.com / yandex.ru
#   - zoho.com / rediffmail.com / mail.com
#
# When a customer disputes a domain in this file, add it to the EXCLUDED
# set in scripts/buildDisposableDomains.mjs and re-run the build. Do NOT
# remove it from index.json - that file is treated as immutable input.
#
`;

// ---------------------------------------------------------------------------
// Hardcoded exclusions
//
// Legit services that aggregator lists occasionally tag as disposable.
// These are stripped regardless of what the source data says. Add to this
// set when a customer reports a false positive.
// ---------------------------------------------------------------------------

const EXCLUDED = new Set([
  // Privacy / encrypted mail
  'protonmail.com', 'proton.me', 'pm.me',
  'tutanota.com', 'tutamail.com', 'tuta.io',
  'hushmail.com', 'fastmail.com', 'fastmail.fm',
  // Major Chinese providers
  'qq.com', 'sohu.com', '163.com', '126.com', 'yeah.net',
  'sina.com', 'sina.cn', 'aliyun.com',
  // Major US / international providers
  'gmail.com', 'googlemail.com',
  'yahoo.com', 'yahoo.co.uk', 'yahoo.fr', 'yahoo.de', 'yahoo.it',
  'yahoo.es', 'yahoo.com.au', 'yahoo.ca', 'yahoo.com.br', 'ymail.com', 'rocketmail.com',
  'outlook.com', 'outlook.fr', 'outlook.de', 'outlook.it', 'outlook.es',
  'hotmail.com', 'hotmail.co.uk', 'hotmail.fr', 'hotmail.de', 'hotmail.it',
  'icloud.com', 'mac.com', 'me.com',
  'aol.com', 'aim.com',
  'gmx.com', 'gmx.net', 'gmx.de', 'gmx.us', 'gmx.co.uk', 'gmx.fr',
  'live.com', 'live.co.uk', 'live.fr', 'live.de', 'live.it',
  'msn.com',
  // Russian / CIS
  'mail.ru', 'list.ru', 'bk.ru', 'inbox.ru',
  'yandex.com', 'yandex.ru', 'ya.ru',
  // Other mainstream
  'zoho.com', 'zohomail.com',
  'rediffmail.com',
  'mail.com',
  'web.de', 't-online.de',
  'orange.fr', 'wanadoo.fr', 'laposte.net', 'free.fr', 'sfr.fr',
  'libero.it', 'tiscali.it', 'virgilio.it',
  'naver.com', 'daum.net', 'hanmail.net',
  // Business / paid
  'workspace.google.com',
]);

// ---------------------------------------------------------------------------
// Domain shape: must match what we use elsewhere in the codebase.
// ---------------------------------------------------------------------------

const DOMAIN_SHAPE = /^[a-z0-9][a-z0-9.-]*\.[a-z]{2,}$/;
const MARKDOWN_LINK_PREFIX = /^\[([^\]]+)\]/;

/**
 * Extract a clean domain from a raw line. Handles:
 *   - "[example.com](http://example.com)"   markdown-link format
 *   - "*.example.com"                       wildcard prefix
 *   - "https://example.com/path"            full URL
 *   - "user@example.com"                    full address
 *   - "example.com:25"                      host:port
 *   - "Example.COM"                         mixed case
 * Returns null if the line is malformed, on the exclusion list, or doesn't
 * match the domain shape.
 */
function extractDomain(raw) {
  if (typeof raw !== 'string') return null;
  let s = raw.trim();
  if (!s) return null;

  // Strip markdown-link wrapper: [domain](url)
  const m = MARKDOWN_LINK_PREFIX.exec(s);
  if (m) s = m[1];

  s = s.toLowerCase().trim();

  // Strip URL prefixes
  s = s.replace(/^https?:\/\//, '');
  // Strip user@ for full addresses
  if (s.includes('@')) s = s.split('@').pop();
  // Strip wildcard prefix
  s = s.replace(/^\*\./, '');
  // Strip path / query / fragment / port
  s = s.split('/')[0].split('?')[0].split('#')[0].split(':')[0];
  // Strip trailing dots
  s = s.replace(/\.+$/, '');

  if (!DOMAIN_SHAPE.test(s)) return null;
  if (EXCLUDED.has(s)) return null;
  return s;
}

// ---------------------------------------------------------------------------
// Read the curated additions file (optional)
// ---------------------------------------------------------------------------

function readCurated(path) {
  if (HAS_NO_CURATED) return { domains: new Set(), source: '(skipped via --no-curated)' };
  if (!existsSync(path)) return { domains: new Set(), source: '(not present)' };

  const lines = readFileSync(path, 'utf-8').split(/\r?\n/);
  const domains = new Set();
  let dropped = 0;
  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const d = extractDomain(t);
    if (d) domains.add(d);
    else dropped++;
  }
  return { domains, source: path, dropped };
}

// ---------------------------------------------------------------------------
// Read index.json
// ---------------------------------------------------------------------------

function readIndexJson(path) {
  if (!existsSync(path)) {
    console.error(`ERROR: ${path} not found. Place index.json in repo root or pass --input.`);
    process.exit(1);
  }
  let raw;
  try {
    raw = JSON.parse(readFileSync(path, 'utf-8'));
  } catch (err) {
    console.error(`ERROR: ${path} is not valid JSON: ${err.message}`);
    process.exit(1);
  }
  if (!Array.isArray(raw)) {
    console.error(`ERROR: ${path} must be a JSON array of strings.`);
    process.exit(1);
  }
  return raw;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

console.log('');
console.log('=== Disposable domains build ===');
console.log('');
console.log(`Input:    ${INPUT_JSON}`);
console.log(`Curated:  ${CURATED_TXT}`);
console.log(`Output:   ${OUTPUT_TXT}`);
console.log('');

// 1. Read curated overrides
const curated = readCurated(CURATED_TXT);
console.log(`Curated:  ${curated.domains.size.toLocaleString()} domains from ${curated.source}`);
if (curated.dropped) {
  console.log(`          (${curated.dropped.toLocaleString()} curated lines dropped as malformed or excluded)`);
}

// 2. Read index.json
const rawJson = readIndexJson(INPUT_JSON);
console.log(`Source:   ${rawJson.length.toLocaleString()} raw entries from index.json`);

// 3. Parse + filter
let parsed = 0, malformed = 0, policyExcluded = 0;
const fromJson = new Set();
for (const entry of rawJson) {
  if (typeof entry !== 'string') { malformed++; continue; }
  const d = extractDomain(entry);
  if (d) {
    fromJson.add(d);
    parsed++;
    continue;
  }
  // Not parseable as a domain we'd accept. Was it just policy-excluded?
  const pre = entry.trim().toLowerCase().replace(/^\[([^\]]+)\].*$/, '$1').replace(/^\*\./, '');
  if (EXCLUDED.has(pre)) policyExcluded++;
  else malformed++;
}

console.log('');
console.log('Parse results:');
console.log(`  parseable:       ${parsed.toLocaleString()}`);
console.log(`  unique parsed:   ${fromJson.size.toLocaleString()}`);
console.log(`  malformed:       ${malformed.toLocaleString()}`);
console.log(`  policy-excluded: ${policyExcluded.toLocaleString()}`);

// 4. Merge: curated wins (it's our overrides). Both sets are unique already.
const merged = new Set([...curated.domains, ...fromJson]);
console.log('');
console.log(`Merged unique:   ${merged.size.toLocaleString()}`);

// 5. Sort alphabetically, byte-wise (LC_ALL=C equivalent).
//    Default Array.prototype.sort is lexicographic on UTF-16 code units,
//    which matches LC_ALL=C for ASCII-only domain strings.
const sorted = [...merged].sort();

// 6. Final shape-check defense in depth
let finalDropped = 0;
const final = sorted.filter((d) => {
  if (DOMAIN_SHAPE.test(d) && !EXCLUDED.has(d)) return true;
  finalDropped++;
  return false;
});
if (finalDropped) {
  console.log(`Final pass dropped ${finalDropped} entries that slipped through earlier filters.`);
}

// 7. Write output
const out = HEADER + final.join('\n') + '\n';
writeFileSync(OUTPUT_TXT, out, 'utf-8');

const sizeKb = (out.length / 1024).toFixed(1);
console.log('');
console.log(`Wrote ${OUTPUT_TXT}`);
console.log(`  ${final.length.toLocaleString()} entries, ${sizeKb} KB`);
console.log('');
console.log('Next steps:');
console.log('  git diff data/disposable_domains.txt   # review the diff');
console.log('  git add data/disposable_domains.txt');
console.log('  git commit -m "data: refresh disposable domains list"');
console.log('');
