// IndexNow ping utility. POSTs URL updates to api.indexnow.org which forwards to Bing, Yandex, Seznam, and Naver.
// Reads sitemap.xml from the live site by default; can filter by section or take explicit URLs.

import path from 'node:path';
import { execSync } from 'node:child_process';

const BASE_URL = 'https://trovarci.sh';
const HOST = 'trovarci.sh';
const ENDPOINT = 'https://api.indexnow.org/indexnow';
const KEY = process.env.INDEXNOW_KEY;

const args = process.argv.slice(2);
const flags = {
  all: args.includes('--all'),
  blog: args.includes('--blog-only'),
  tools: args.includes('--tools-only'),
  changed: args.includes('--changed'),
  dryRun: args.includes('--dry-run'),
  help: args.includes('--help') || args.includes('-h'),
  urls: args.filter(a => a.startsWith('http')),
};

function usage() {
  console.log(`
IndexNow ping utility for ${HOST}

Usage:
  node --env-file=.env scripts/indexnowPing.mjs [flags] [urls...]

Modes (choose one):
  --all           Ping every URL in the sitemap (use for initial submission)
  --blog-only     Ping only /blog/ post URLs from the sitemap
  --tools-only    Ping only tool pages (/score, /domain, /verify, /verify-number, /smtp-test, /records)
  --changed       Ping URLs whose blog posts or route files changed in the last git commit (route changes validated against sitemap)
  <urls>          Ping specific URLs passed as CLI arguments

Options:
  --dry-run       Print URLs that would be pinged; do not POST
  -h, --help      Show this help

Examples:
  node --env-file=.env scripts/indexnowPing.mjs --all --dry-run
  node --env-file=.env scripts/indexnowPing.mjs --changed
  node --env-file=.env scripts/indexnowPing.mjs https://trovarci.sh/blog/new-post

Env vars required:
  INDEXNOW_KEY    Generated by scripts/indexnowSetup.mjs
`);
}

async function fetchSitemapUrls() {
  const res = await fetch(`${BASE_URL}/sitemap.xml`);
  if (!res.ok) throw new Error(`Sitemap fetch failed: HTTP ${res.status}`);
  const xml = await res.text();
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);
}

function filterUrls(urls) {
  // Exclude /blog index itself from --blog-only; we want post URLs only.
  if (flags.blog) return urls.filter(u => u.includes('/blog/') && u !== `${BASE_URL}/blog`);
  if (flags.tools) return urls.filter(u => /\/(score|domain|verify|verify-number|smtp-test|records)$/.test(u));
  return urls;
}

function getChangedBlogUrls() {
  try {
    // Compares HEAD against previous commit. On very first commit HEAD~1 does not exist.
    const output = execSync('git diff --name-only HEAD~1 HEAD -- content/blog/', { encoding: 'utf-8' });
    return output
      .split('\n')
      .filter(line => line.endsWith('.md'))
      .map(line => path.basename(line, '.md'))
      .map(slug => `${BASE_URL}/blog/${slug}`);
  } catch {
    console.warn('[warn] git diff failed; no changed URLs detected (expected on first commit or shallow clones).');
    return [];
  }
}

// Map a Remix flat-routes filename to its URL path. Returns null for API routes,
// catchalls, and any route containing a dynamic $ segment.
function routeFileToUrl(filename) {
  let name = filename.replace(/\.(jsx|js|tsx|ts)$/, '');

  if (name === '$' || name.startsWith('$')) return null;
  if (name.startsWith('api.')) return null;
  if (name.split('.').some(seg => seg.startsWith('$'))) return null;

  if (name === '_index') return '/';

  // Preserve literal dots written as [.]  (e.g. sitemap[.]xml.jsx -> /sitemap.xml)
  const DOT_HOLDER = '\u0001';
  name = name.replace(/\[\.\]/g, DOT_HOLDER);

  let segments = name.split('.').map(s => s.replace(/_$/, ''));
  if (segments[segments.length - 1] === '_index') segments.pop();

  return '/' + segments.join('/').replace(new RegExp(DOT_HOLDER, 'g'), '.');
}

function getChangedRouteFiles() {
  try {
    const output = execSync('git diff --name-only HEAD~1 HEAD -- app/routes/', { encoding: 'utf-8' });
    return output
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0)
      .map(line => path.basename(line));
  } catch {
    return [];
  }
}

// Merge blog and route changes. Route candidates are validated against the live
// sitemap so admin, auth, API, and dynamic detail pages never leak to IndexNow.
async function getChangedUrls() {
  const blogUrls = getChangedBlogUrls();
  const routeFiles = getChangedRouteFiles();

  const routeCandidates = routeFiles
    .map(routeFileToUrl)
    .filter(Boolean)
    .map(p => `${BASE_URL}${p}`);

  if (routeCandidates.length === 0) {
    return blogUrls;
  }

  let sitemapSet;
  try {
    sitemapSet = new Set(await fetchSitemapUrls());
  } catch (err) {
    console.warn(`[warn] sitemap fetch failed, skipping route validation: ${err.message}`);
    return blogUrls;
  }

  const validated = routeCandidates.filter(u => sitemapSet.has(u));
  const skipped = routeCandidates.filter(u => !sitemapSet.has(u));

  if (skipped.length > 0) {
    console.log(`[info] ${skipped.length} route change(s) not in sitemap, skipping:`);
    for (const s of skipped) console.log(`         ${s}`);
  }

  return [...new Set([...blogUrls, ...validated])];
}

async function ping(urls) {
  const body = {
    host: HOST,
    key: KEY,
    keyLocation: `${BASE_URL}/${KEY}.txt`,
    urlList: urls,
  };

  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
    body: JSON.stringify(body),
  });

  const text = await res.text();
  return { status: res.status, text };
}

async function main() {
  if (flags.help || args.length === 0) {
    usage();
    process.exit(0);
  }

  if (!KEY) {
    console.error('[FAIL] INDEXNOW_KEY env var not set.');
    console.error('       Run scripts/indexnowSetup.mjs to generate one, then export it or use --env-file=.env.');
    process.exit(1);
  }

  let urls = [];

  if (flags.urls.length > 0) {
    urls = flags.urls;
  } else if (flags.changed) {
    urls = await getChangedUrls();
  } else if (flags.all || flags.blog || flags.tools) {
    console.log(`Fetching sitemap: ${BASE_URL}/sitemap.xml`);
    const all = await fetchSitemapUrls();
    urls = filterUrls(all);
  } else {
    usage();
    process.exit(1);
  }

  if (urls.length === 0) {
    console.log('[skip] No URLs to ping.');
    process.exit(0);
  }

  console.log(`\nURLs to ping (${urls.length}):`);
  for (const u of urls) console.log(`  ${u}`);

  if (flags.dryRun) {
    console.log('\n[dry-run] No POST sent.');
    process.exit(0);
  }

  console.log(`\nPOSTing to ${ENDPOINT} ...`);
  try {
    const { status, text } = await ping(urls);
    if (status === 200 || status === 202) {
      console.log(`[OK] IndexNow accepted ${urls.length} URL(s). status=${status}`);
      process.exit(0);
    }
    console.error(`[FAIL] IndexNow returned status=${status}`);
    if (text) console.error(text);
    process.exit(1);
  } catch (err) {
    console.error('[FAIL] Ping failed:', err.message);
    process.exit(1);
  }
}

main();
